# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GeoXplore' do

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for GeoXplore
   pod 'Alamofire', '~> 4.7'
   pod 'Mapbox-iOS-SDK', '~> 3.7'
   pod 'ObjectMapper', '~> 3.1'
   pod 'SwiftKeychainWrapper'
   pod 'NVActivityIndicatorView'
end
