# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'
 use_frameworks!


target 'GeoXplore' do

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # Pods for GeoXplore
   pod 'Alamofire', '~> 4.7'
   pod 'Mapbox-iOS-SDK', '~> 3.7'
   pod 'ObjectMapper', '~> 3.1'
   pod 'SwiftKeychainWrapper'
   pod 'NVActivityIndicatorView'

   post_install do |installer|
     installer.pods_project.build_configurations.each do |config|
       config.build_settings.delete('CODE_SIGNING_ALLOWED')
       config.build_settings.delete('CODE_SIGNING_REQUIRED')
     end
   end
end
